### ISSUE TITLE
matchCommunityTests: false not working

### ISSUE THREAD

**Issue by blmyr** [Modernizr/grunt-modernizr#86]
I have grunt modernizr set up with the following options:

``` js
devFile: 'remote',
outputFile: 'modernizr.js',
uglify: false,
parseFile: true,
matchCommunityTests: false
```

I have a css test file with the following content:

``` css
.notification {
    background: blue;
}

.flexbox {
    background: red;
}

.no-csstransforms {
    background: black;
}
```

No matter how I set the `matchCommunityTest`option it will always match `.notification` and downloads the community test. I am using the class `.notification` in a bigger project and don't want to change it.
